### PR TITLE
Enable monaco editor

### PR DESCRIPTION
**Pull request by volodymyrkochyn**
We are running some testing

### CODE REVIEW

**Review by alaindargelas — CHANGES_REQUESTED** [review]
@KochynVolodymyr, looks like a repeat directory name issue: 

2024-01-22T15:10:12.1939794Z gmake[3]: Leaving directory '/home/runner/work/Raptor/Raptor/build'
2024-01-22T15:10:12.1959103Z gmake[3]: Entering directory '/home/runner/work/Raptor/Raptor/build'
2024-01-22T15:10:13.7257470Z Error copying directory from "/home/runner/work/Raptor/Raptor/FOEDAG_rs/third_party/monaco-editor/monaco-editor" to "/home/runner/work/Raptor/Raptor/build/FOEDAG_rs/share/raptor/etc/monaco-editor/monaco-editor".
2024-01-22T15:10:13.7261751Z gmake[3]: *** [FOEDAG_rs/CMakeFiles/raptor_gui-bin.dir/build.make:263: FOEDAG_rs/bin/raptor] Error 1
2024-01-22T15:10:13.7263357Z gmake[3]: *** Deleting file 'FOEDAG_rs/bin/raptor'
2024-01-22T15:10:13.7292886Z gmake[3]: Leaving directory '/home/runner/work/Raptor/Raptor/build'

**Review by alain-rs — APPROVED** [review]

**Comment by alaindargelas** [comment]
@ravikiranchollangi , I'm getting:

Extracting monaco-editor tgz package: 0.45.0 ...
'tar' '-xf' '/home/alain/os-fpga/Raptor/FOEDAG_rs/FOEDAG/third_party/monaco-editor/monaco-editor-0.45.0.tgz'

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
CMake Error at FOEDAG_rs/FOEDAG/third_party/monaco-editor/CMakeLists.txt:26 (message):
  monaco editor extraction failed!


-- Configuring incomplete, errors occurred!
See also "/home/alain/os-fpga/Raptor/build/CMakeFiles/CMakeOutput.log".
make: *** [Makefile:46: run-cmake-release] Error 1

**Comment by ravikiranchollangi** [comment]
> @ravikiranchollangi , I'm getting:
> 
> 
> 
> Extracting monaco-editor tgz package: 0.45.0 ...
> 
> 'tar' '-xf' '/home/alain/os-fpga/Raptor/FOEDAG_rs/FOEDAG/third_party/monaco-editor/monaco-editor-0.45.0.tgz'
> 
> 
> 
> gzip: stdin: unexpected end of file
> 
> tar: Unexpected EOF in archive
> 
> tar: Unexpected EOF in archive
> 
> tar: Error is not recoverable: exiting now
> 
> CMake Error at FOEDAG_rs/FOEDAG/third_party/monaco-editor/CMakeLists.txt:26 (message):
> 
>   monaco editor extraction failed!
> 
> 
> 
> 
> 
> -- Configuring incomplete, errors occurred!
> 
> See also "/home/alain/os-fpga/Raptor/build/CMakeFiles/CMakeOutput.log".
> 
> make: *** [Makefile:46: run-cmake-release] Error 1
> 
> 

Please clean and try. We have the same running extraction running on CI. I will check with @volodymyrkochyn since we had some Ubuntu specific build issues but unrelated to this afaik.

**Comment by alaindargelas** [comment]
It is really about the file format. I have the latest "tar" for Ubuntu 22.04:

os-fpga/Raptor$ tar -xf /home/alain/os-fpga/Raptor/FOEDAG_rs/FOEDAG/third_party/monaco-editor/monaco-editor-0.45.0.tgz

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

Can you use a more standard way to create the tar file:
tar xvzf  ...... monaco-editor-0.45.0.tar.gz

**Comment by alaindargelas** [comment]
rm -rf Raptor and 
new clone fixes it.
make clean didn't fix it.

**Pull request merged**
