### PR TITLE
Port latest FOEDAG_rs

### PR DESCRIPTION
**Pull request by chungshien-chai**

### CODE REVIEW

**Comment by alaindargelas** [comment]
@chungshien-chai this PR is missing:
https://github.com/os-fpga/Raptor/pull/1604/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52

**Comment by chungshien-chai** [comment]
Found that Makefile become a binary (from github perspective) because of weird symbol in line 115 (seems to be so becuase of changelist https://github.com/os-fpga/Raptor/commit/699ab86cd7d665f987b607fc2e177fc3b265231b)

image

**Comment by alaindargelas** [comment]
Ooops my mistake, some emacs key I must have hit. Can you fix?

**Comment by chungshien-chai** [comment]
Already fixed as part of my PR.

**Pull request merged**
