### PR TITLE
build vpr_latest in Raptor

### PR DESCRIPTION
**Pull request by serge-dsa**

### CODE REVIEW

**Comment by alaindargelas** [comment]
@serge-dsa , please check the valgrind build error, it said cannot copy planner executable to dbuild directory (Valgrind is a debug build). Please check you correctly produce debug and release build with your changes in this PR (Make a debug build at Raptor level locally), once you confirm, I'll merge.

**Review by alaindargelas — CHANGES_REQUESTED** [review]
@serge-dsa , please check the valgrind build error, it said cannot copy planner executable to dbuild directory (Valgrind is a debug build). Please check you correctly produce debug and release build with your changes in this PR (Make a debug build at Raptor level locally), once you confirm, I'll merge.

**Comment by serge-rs** [comment]
@alaindargelas I'll redo this PR - will reimplement the submodule checkout of vpr_latest. I'll make another PR and will confirm valgrind build locally.

**Comment by alaindargelas** [comment]
@serge-dsa , closing this PR

**Pull request closed without merging**
